name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: gh-deploy
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install lightgallery
      - run: mkdocs gh-deploy --force
      
  compress:
    runs-on: ubuntu-latest
    outputs:
      branch: deploy
    steps:
        - uses: stefh/ghaction-CompressFiles@v1
          with:
            depth: 5
            extensions: '.css,.html,.js,.map,.ttf,.otf,.eot,.svg,.woff,.woff2,.xml,.txt,.md'
            tools: 'brotli,gzip'
